default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: bevatel_backend_task_development

test:
  <<: *default
  database: bevatel_backend_task_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "test" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>